Repository nss-evening-cohort-14/clown-college-dashboard-clown-college-dashboard, pull requests merged in 2021-04, with the labels that each got.

#34 NavBar Redirect Bug Fixed
  src/javascripts/components/navbar.js
  src/javascripts/events/navEvents.js
  src/javascripts/views/homeView.js
  src/javascripts/views/startApp.js
  src/styles/assets/universityLogo.jpeg
Labels: documentation

#35 fixed delete functionality lessons & teachers
  src/javascripts/components/teachers/showAllTeachers.js
  src/javascripts/events/teacherEvents.js
  src/javascripts/helpers/db/lessons.json
  src/javascripts/helpers/db/teachers.json
  src/javascripts/helpers/teacherHelper.js
Labels: documentation

#38 Fixed all student specific bugs
  src/javascripts/components/students/showAllStudents.js
  src/javascripts/components/students/showEditStudentForm.js
  src/javascripts/components/students/studentForm.js
  src/javascripts/events/studentEvents.js
  src/javascripts/helpers/db/students.json
  src/javascripts/helpers/signOut.js
  src/javascripts/helpers/studentHelper.js
Labels: bug

#40 Fixed firebase
  src/javascripts/components/classes/classForm.js
  src/javascripts/components/classes/showAllClasses.js
  src/javascripts/components/lessons/lessonForm.js
  src/javascripts/components/lessons/showAllLessons.js
  src/javascripts/components/majors/majorForm.js
  src/javascripts/components/majors/showAllMajors.js
  src/javascripts/components/students/showAllStudents.js
  src/javascripts/components/students/studentForm.js
  src/javascripts/components/teachers/showAllTeachers.js
  src/javascripts/components/teachers/teacherForm.js
  src/javascripts/events/classEvents.js
  src/javascripts/events/lessonEvents.js
  src/javascripts/events/majorEvents.js
  src/javascripts/events/studentEvents.js
  src/javascripts/events/teacherEvents.js
  src/javascripts/helpers/classHelper.js
  src/javascripts/helpers/db/allDB.json
Labels: enhancement

#41 just have the double add bug left
  src/javascripts/helpers/classHelper.js
Labels: enhancement

#42 fixed image issue
  src/javascripts/components/students/showAllStudents.js
  src/javascripts/components/teachers/showAllTeachers.js
  src/javascripts/helpers/db/majors.json
  src/styles/main.scss
Labels: enhancement
